
services:
  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    container_name: quarkus-app-native
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    volumes:
      - h2-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  h2-data:
    name: quarkus-h2-data

networks:
  default:
    name: quarkus-network
    driver: bridge