services:
  quarkus-app:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0```
    volumes:
      - h2-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  h2-data:

networks:
  default:
    name: quarkus-network
    driver: bridge