
services:
  quarkus-app-micro:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    container_name: quarkus-app-native-micro
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    volumes:
      - h2-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  h2-data:
    name: quarkus-h2-data

networks:
  default:
    name: quarkus-network
    driver: bridge